# Generated by Django 3.2.9 on 2021-11-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211111_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact2',
            new_name='infos',
        ),
    ]
