# Generated by Django 3.2.9 on 2021-11-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact2_infos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='infos',
            new_name='Contact',
        ),
    ]
